README.md
It's easy to skim over the Docker pre-requisite as organized. This should make it harder to miss and make it clear that there are 2 steps.
=> Make pre-requisites more scannable

CONTRIBUTING.md
The template pointed to LICENSE.md but this repo is using LICENSE
updated link to point to mcp's license file
Closes:
=> Update CONTRIBUTING.md to fix link to LICENSE file

cmd/github-mcp-server/main.go
- **create a config struct for running the server**
- **pretty print json**
Closes: #113
Introduces a new flag `pretty-print-json` which will format json output from the server for easier visualization.
As the list of configuration options was growing, I opted to add a config struct instead of adding one more to the pile.
(partial output in the screenshot below)
With all of this code in main, there isn't a good way to add tests here and it felt a bit out of place to add to pkg/github/server.go
A refactor would be very helpful to make this easier.
I did not add a new option to the launch.json for it, as I feel like it is still best to be disabled by default.
A future enhancement might be to incorporate https://github.com/cli/go-gh/blob/61bf393cf4aeea6d00a6251390f5f67f5b67e727/pkg/jsonpretty …
=> pretty print json

.github/workflows/code-scanning.yml
In order to support PRs from forks, we cannot use default setup at this juncture, so switching to advanced setup.
=> chore: add code scanning advanced setup yml

pkg/github/server.go
The `createIssue` tool is added twice.
=> Removed duplicated createIssue tool definition

pkg/github/repository_resource.go
Just one misspelling in 9k lines of code!
=> Fix a typo in repository_resource.go

cmd/github-mcp-server/main.go, pkg/github/server.go
Just noticed that this was not wired up, and it should be. The server has a version param that was still hard-coded.
=> chore: pass version through to server

pkg/github/code_scanning.go, pkg/github/code_scanning_test.go, pkg/github/server.go
Exports code scanning functions so they are part of the package public interface.
=> chore: export code scanning funcs

pkg/github/pullrequests.go, pkg/github/pullrequests_test.go, pkg/github/server.go
=> chore: export pr funcs

pkg/github/repositories.go, pkg/github/repositories_test.go, pkg/github/repository_resource.go, pkg/github/repository_resource_test.go, pkg/github/server.go
Export repository funcs to the public interface.
=> chore: export repository funcs

pkg/github/code_scanning.go, pkg/github/issues.go, pkg/github/pullrequests.go, pkg/github/repositories.go, pkg/github/search.go, pkg/github/server.go, pkg/github/server_test.go
Export the remaining tool funcs and helpers.
=> chore: export remaining + helpers

.github/workflows/docker-publish.yml
This pull request includes a significant update to the `docker-publish.yml` workflow file. The primary change is the addition of multiple tagging rules for Docker images, which enhances the flexibility and control over how images are tagged during the publishing process.
Enhancements to Docker image tagging:
* [`.github/workflows/docker-publish.yml`](diffhunk://#diff-5b21991be47c2922383bdc0b6bf00b65af7db51b82d049dd8d6ad03e3d37ac98R69-R82): Added various tagging rules including schedule-based, branch-based, tag-based, pull request-based, semantic versioning patterns, SHA, edge, match, and PEP 440. Additionally, a custom rule was added to prevent pre-releases from getting the "latest" tag.
Closes [#156](https://github.com/github/github-mcp-server/issues/156)`
=> fix: enhance Docker publish workflow with additional tagging options

.github/workflows/goreleaser.yml
Closes: #173
I pushed a tag v0.1.2-0 to the fork repository https://github.com/suzuki-shunsuke/github-mcp-server and confirmed attestations were generated.
https://github.com/suzuki-shunsuke/github-mcp-server/actions/runs/14326892487/job/40153957850
https://github.com/suzuki-shunsuke/github-mcp-server/attestations/6157885
```sh
gh release download -R suzuki-shunsuke/github-mcp-server v0.1.2-0
while read -r asset; do
echo "$asset"
gh attestation verify "$asset" \
-R suzuki-shunsuke/github-mcp-server \
--signer-workflow suzuki-shunsuke/github-mcp-server/.github/workflows/goreleaser.yml
done < <(ls)
```
<details>
<summary>Result</summary>
```
github-mcp-server_0.1.2-0_checksums.txt
Loaded digest sha256:6aa7d0c3c21532ed26b2685bc2cbe4275390b949e2b0402e259ccca9bbc32165 for …
```
=> Generate GitHub Artifact Attestations

README.md
Some identifiers were recently exported for internal use, but this is not a commitment to a stable API, so let's document that.
=> Indicate Go API stability in README

cmd/github-mcp-server/main.go
Reverts https://github.com/github/github-mcp-server/pull/114
This change breaks the protocol, which expects json to be separated by newlines. To avoid confusion, this is being reverted.
Instead, users are encouraged to use:
1. `mcpcurl`
1. use `script/prettyprint-log` to format log results
=> remove pretty print json flag

pkg/github/issues_test.go, pkg/github/server.go
When attempting to use Claude for MCP tooling, any optional arrays it currently submits a nil value instead of an empty array which results in a returned error. This change adjusts that to return an empty array instead of an error for nil optional arrays.
Closes: https://github.com/github/github-mcp-server/issues/193
=> Fix handling nil values for optional string array parameters,

cmd/github-mcp-server/main.go, pkg/github/code_scanning.go, pkg/github/code_scanning_test.go, pkg/github/issues.go, pkg/github/issues_test.go, pkg/github/pullrequests.go, pkg/github/pullrequests_test.go, pkg/github/repositories.go, pkg/github/repositories_test.go, pkg/github/repository_resource.go, pkg/github/repository_resource_test.go, pkg/github/search.go, pkg/github/search_test.go, pkg/github/server.go, pkg/github/server_test.go
In order to facilitate multi-user (MCP Host) to server communication, we need to support new `*github.Client` clients per request, rather than globally.
This change is a NOOP that makes it possible.
=> chore: groundwork for multi-user to server

pkg/github/server.go
Adds support the the underlying mcp-go `ServerOptions` so that [hook functions](https://github.com/mark3labs/mcp-go/blob/main/server/hooks.go#L84-L107) can be attached to the server.
=> Allow passing through server options

pkg/github/repositories_test.go
Went to cut a PR upstream and realized I missed [this pre-defined endpoint pattern](https://github.com/migueleliasweb/go-github-mock/blob/master/src/mock/endpointpattern.go#L2875-L2878) when checking for work on #216.
=> Prefer already-defined endpoint mock

cmd/github-mcp-server/main.go
This gets you things like: `github-mcp-server/<version> (Visual Studio Code - Insiders/<version>)` if provided by the host.
=> chore: extend user agent

README.md
In working on contributing to https://github.com/github/github-mcp-server/pull/225, I found this area of the instructions could use more clarity. Hopefully this is clearer and provides additional instructions on how to specify the output location of the build and configure the server to use the built executable.
=> Add clarity to the "Build from source" option

pkg/github/notifications.go, pkg/github/server.go
**Note:** Target branch is `notifications-tooling` https://github.com/github/github-mcp-server/pull/225
- `mark_notification_done: Mark a specific notification thread as done
- I largely copied `mark_notification_read`
- For the param `threadId`, `WithNumber` ran into some issues, so I kept the param as a string. I'm open to suggestions.
=> Add "Mark notification as done" functionality

pkg/github/pullrequests.go
This updates the JSON schema for the `create_pull_request_review` tool to make all of the array properties required as per OpenAI's function calling API requirements, _but_ make the optional properties nullable.
=> fix: update json schema for `create_pull_request_review`

README.md
To avoid confusion, keep the readme update to right before semver release.
=> chore: update readme for tool parititioning

pkg/github/pullrequests.go
Windsurf is erroring on the `create_pull_request` tool because we're using an array of types to make fields nullable. This PR uses `anyOf` instead and should fix the issue.
Closes: #318
=> fix: use anyOf instead of nullable type array

e2e/README.md, e2e/e2e_test.go
Whilst reviewing dependabot updates, I really wanted a fast way to build a Docker image, start the server, call a tool and validate the result, as opposed to [doing it manually](https://github.com/github/github-mcp-server/pull/323#pullrequestreview-2784138391).
The primary audience for the current e2e test is myself, and any other maintainer, and in future possibly other contributors. See the readme for some limitations on the approach, which is why I don't necessarily want to make all contributors first class audience, though there's no reason that it couldn't be used.
The implementation is pretty MVP, and that's also intentional, until we see if and where it provides value.
=> Add simple e2e test

pkg/github/code_scanning.go, pkg/github/context_tools.go, pkg/github/dynamic_tools.go, pkg/github/issues.go, pkg/github/pullrequests.go, pkg/github/repositories.go, pkg/github/search.go, pkg/github/secret_scanning.go, pkg/github/tools.go, pkg/toolsets/toolsets.go
Closes: https://github.com/github/github-mcp-server/issues/306
We can provide tool annotations as part of the tool specification. This PR sets the descriptions (with ability to override translations), and the `ReadOnlyHint`.
I tried to make the descriptions more human readable as intended also. These are the translation file entries:
```json
"TOOL_ADD_ISSUE_COMMENT_USER_TITLE": "Add comment to issue",
"TOOL_ADD_PULL_REQUEST_REVIEW_COMMENT_USER_TITLE": "Add review comment to pull request",
"TOOL_CREATE_BRANCH_USER_TITLE": "Create branch",
"TOOL_CREATE_ISSUE_USER_TITLE": "Open new issue",
"TOOL_CREATE_OR_UPDATE_FILE_USER_TITLE": "Create or update file",
"TOOL_CREATE_PULL_REQUEST_REVIEW_USER_TITLE": "Submit pull request review",
"TOOL_CREATE_PULL_REQUEST_USER_TITLE": "Open new pull request", …
```
=> feat: provide tool annotations

README.md
search_code was misalligned. fixed it in README.
Closes:
=> small doc change : fixing formatting in list of tool functions 

README.md
The `.vscode/mcp.json` configuration example in the README.md does not appear to work with the snippet provided. There is a note that indicates that the mcp key is not needed. More specifically, the mcp key needs to be removed for the `.vscode/mcp.json` configuration to work. To make things simpler and easier to get started, we provide two example snippets to get started depending on which settings file is used.
Before:
After:
Version:
```
Version: 1.99.1 (Universal)
Commit: 7c6fdfb0b8f2f675eb0b47f3d95eeca78962565b
Date: 2025-04-04T15:58:59.624Z (4 days ago)
Electron: 34.3.2
ElectronBuildId: 11161073
Chromium: 132.0.6834.210
Node.js: 20.18.3
V8: 13.2.152.41-electron.0
OS: Darwin x64 24.3.0
```
=> Update README.md to remove mcp key on .vscode/mcp.json example

cmd/github-mcp-server/main.go, e2e/e2e_test.go
Fixes https://github.com/github/github-mcp-server/issues/307
You can run the e2e tests and see a failure by adjusting `GITHUB_TOOLSETS` and running:
```
GITHUB_MCP_SERVER_E2E_TOKEN=foo go test -v -run  "TestToolsets" --tags e2e ./e2e
```
=> Ensure toolsets are configurable via env var

e2e/README.md, e2e/e2e_test.go, pkg/github/helper_test.go, pkg/github/repositories.go, pkg/github/repositories_test.go, pkg/github/tools.go
Add git tag functionality, including:
- List repository tags
- Get tag details
- Support for tag-based content access
This enables basic read-only tag management through the MCP server API.
Closes:  https://github.com/github/github-mcp-server/issues/344
=> feat: Add support for Git tag operations

cmd/github-mcp-server/main.go, e2e/README.md, e2e/e2e_test.go, internal/ghmcp/server.go
While working on other issues, I often found myself experiencing failures that were not easy to debug given the black box nature of the e2e tests. Now we can use `GITHUB_MCP_SERVER_E2E_DEBUG=true` to run an inprocess server version of the server, allowing for breakpointing. Open to renaming the env var to indicate exactly what it does, rather than debug. See image:
```
➜  github-mcp-server git:(wm/debug-e2e-tests) GOMAXPROCS=1 GITHUB_MCP_SERVER_E2E_TOKEN=$(gh auth token) go test -v -count=1 --tags e2e ./e2e
=== RUN   TestGetMe
=== PAUSE TestGetMe
=== RUN   TestToolsets
=== PAUSE TestToolsets
=== RUN   TestTags
=== PAUSE TestTags
=== CONT  TestGetMe
e2e_test.go:49: Building Docker image for e2e tests...
e2e_test.go:122: Starting Stdio MCP client...
--- PASS: TestGetMe (3.07s)
=== CONT …
```
=> Support debugging e2e tests

cmd/mcpcurl/README.md
When ```bash is used for a code fence, bash keywords such as "for" and "in" get rendered with syntax highlighting. Switching to ```console avoids this distraction.
Closes:
=> Change code fence to neutral ```console

.github/workflows/lint.yaml, .golangci.yml, CONTRIBUTING.md, cmd/mcpcurl/main.go, internal/ghmcp/server.go, pkg/github/repositories.go, pkg/translations/translations.go
Use the latest version of `golangci-lint` and fix the CI workflow.
Closes: #378
=> feat: upgrade golangci-lint to v2

e2e/e2e_test.go, pkg/github/repositories.go, pkg/github/repositories_test.go, pkg/github/tools.go
This adds a tool that matches the behavior of [this API endpoint](https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#delete-a-file). This is needed since the `create_or_update_file` tool doesn't allow deletion.
=> feat: add DeleteFile tool to delete files from GitHub repositories

README.md, e2e/e2e_test.go, pkg/github/helper_test.go, pkg/github/pullrequests.go, pkg/github/pullrequests_test.go, pkg/github/tools.go
Closes: #374
This PR adds the `request_copilot_review` tool, which...requests reviews from copilot on PRs where possible. It is an MVP implementation that doesn't try to do anything particularly clever around only exposing the tool for hosts that support it, or playing nice with various error messages that might come back.
=> Add ability to request Copilot reviews via MCP

pkg/github/context_tools.go
This fixes the description for the `reason` argument in the `get_me` tool.
=> fix: update `get_me` reason arg description

pkg/github/context_tools.go
A lot of times the get-me tool is called multiple times in a row, which is redundant. This attempts to address this, by explaining to the model it will not be updated normally.
=> Alter the description of get-me to reduce redundant repeat calls

.github/workflows/lint.yaml
=> feat: add `golangci-lint-action` to the `lint` workflow

e2e/e2e_test.go, internal/githubv4mock/objects_are_equal_values.go, internal/githubv4mock/objects_are_equal_values_test.go, pkg/github/issues.go, pkg/github/issues_test.go, pkg/github/tools.go
Closes: #398 
This adds a new tool `assign_copilot_to_issue`, which...assigns copilot to an issue.
```
➜  github-mcp-server git:(398-add-a-tool-to-assign-copilot-to-issues) GOMAXPROCS=1 GITHUB_MCP_SERVER_E2E_HOST=https://github.com GITHUB_MCP_SERVER_E2E_TOKEN=$(gh auth token) go test -v -count=1 --run TestAssignCopilotToIssue --tags e2e ./e2e
=== RUN   TestAssignCopilotToIssue
=== PAUSE TestAssignCopilotToIssue
=== CONT  TestAssignCopilotToIssue
e2e_test.go:79: Building Docker image for e2e tests...
e2e_test.go:162: Starting Stdio MCP client...
e2e_test.go:959: Getting current user...
e2e_test.go:988: Creating repository williammartin/github-mcp-server-e2e-TestAssignCopilotToIssue-1747756871756...
e2e_test.go:1011: Creating issue in …
```
=> Support assigning copilot to issues

pkg/github/pullrequests.go
Closes: https://github.com/github/github-mcp-server/issues/435
The `add_pull_request_review_comment_to_pending_review` tool mention the `get_line_number_in_pull_request_file` tool to be used to get line number. But this tool does not exists.
https://github.com/github/github-mcp-server/blob/e9f748f246761fb0769e2a5611003939a6274872/pkg/github/pullrequests.go#L1053
=> Remove non-existent get_line_number_in_pull_request_file tool reference

Dockerfile
The current Dockerfile uses `CMD ["./github-mcp-server", "stdio"]` which causes issues when container orchestration tools try to append additional arguments. This results in the entire CMD being replaced rather than arguments being appended.
When using only `CMD`, container runtimes replace the entire command when additional arguments are provided. This breaks argument passing in tools like ToolHive, Kubernetes, and other container orchestrators.
Implement Docker best practices by using:
- `ENTRYPOINT` for the executable that should always run
- `CMD` for default arguments that can be overridden/appended to
**Before:**
```dockerfile
CMD ["./github-mcp-server", "stdio"]
```
**After:**
```dockerfile
ENTRYPOINT ["./github-mcp-server"]
CMD ["stdio"]
```
1. **Proper argument handling**: …
=> fix: use ENTRYPOINT and CMD for proper argument handling

README.md
Document support for GitHub Enterprise Cloud with data residency (ghe.com) in the readme.
=> Add GitHub Enterprise Cloud with data residency (ghe.com) to readme

pkg/github/search.go, pkg/github/search_test.go
There is little use in most of the fields returned by the `search_users` function, as they are reproducible easily by knowing the user handle, or not relevant. The profile URL is useful as it encourages the LLM to format the handle as a link, which is good, I think.
Here is an example showing that the "missing" data is easily re-constructed by the LLM:
=> Reduce fields in `search_users` response

pkg/github/code_scanning.go, pkg/github/context_tools.go, pkg/github/dynamic_tools.go, pkg/github/issues.go, pkg/github/notifications.go, pkg/github/pullrequests.go, pkg/github/repositories.go, pkg/github/search.go, pkg/github/secret_scanning.go, pkg/github/server.go, pkg/github/server_test.go, pkg/github/tools.go
1. Export `ToBoolPtr` and `RequiredParam` functions from the github package.
2. Clean up the type assertion in `RequiredParam`
=> Export `ToBoolPtr` and `RequiredParam`

README.md
Making it clear that you need the latest version of VS Code installed for it work. We've had some folks getting tripped up on auth because they  haven't installed the latest VS code version.
=> Update README.md to prompt VS Code version update

README.md
This pull request adds missing descriptions for several tools in the codebase. The changes improve code clarity and maintainability by ensuring that each tool is properly documented. Please review the updates and let me know if further adjustments are needed.
=> Add missing tool descriptions

pkg/raw/raw.go
Update `newRequest` to accept a `context.Context` param and attach it to the generated `http.Request` using `withContext`.
This change ensures that trace contexts are correctly propagated, supporting distributed tracing in the remote MCP server.
=> Add ctx propagation to raw api request

pkg/github/issues.go, pkg/github/tools.go, pkg/toolsets/toolsets.go
This PR adds a prompt that assigns the Coding Agent to multiple tasks in a specified GitHub repository, validating first if they are clear enough to assign.
- Adds first Prompt to the codebase
- Adds Prompt support to toolsets. 
```
--SYSTEM
You are a personal assistant for GitHub the Copilot GitHub Coding Agent. Your task is to help the user assign tasks to the Coding Agent based on their open GitHub issues. You can use assign_copilot_to_issue tool to assign the Coding Agent to issues that are suitable for autonomous work, and search_issues tool to find issues that match the user's criteria. You can also use list_issues to get a list of issues in the repository.
--USER
Please go and get a list of the most recent 10 issues from the SamMorrowDrums/pigs-facts GitHub repository
--ASSISTANT …
```
=> Add in an assign copilot prompt

pkg/github/repositories.go
Hopefully takes a small step towards addressing complaints that this tool is incorrectly called when models are trying to adjust local files.
=> Adjust `create_or_update_file` description to try avoid incorrect selection

docs/error-handling.md, internal/ghmcp/server.go, pkg/errors/error.go, pkg/errors/error_test.go, pkg/github/__toolsnaps__/create_or_update_file.snap, pkg/github/__toolsnaps__/list_commits.snap, pkg/github/actions.go, pkg/github/code_scanning.go, pkg/github/code_scanning_test.go, pkg/github/context_tools.go, pkg/github/issues.go, pkg/github/notifications.go, pkg/github/notifications_test.go, pkg/github/pullrequests.go, pkg/github/pullrequests_test.go, pkg/github/repositories.go, pkg/github/repositories_test.go, pkg/github/search.go, pkg/github/search_test.go, pkg/github/secret_scanning.go, pkg/github/secret_scanning_test.go
Primarily for the remote server, this is the minimal approach @omgitsads and I could find to enable us to store API errors on the context, so that we can use the error types and http status codes etc. to derive the nature of failures, so that we can understand if failed tool calls occur due to:
- rate limiting
- authentication issues
- 404
- 500s from API etc.
Without this knowledge it's hard for us to validate if changes break things or not.
This is additionally frustrated by the fact mcp-go currently doesn't propagate context through each next step, and so we have concluded that if we create a value pointer on the context, we can edit the values without needing to propagate the context, and we are using this to be able to implement the aforementioned middleware, which can then extract …
=> Enable use of error middleware

pkg/github/__toolsnaps__/get_pull_request_files.snap, pkg/github/pullrequests.go, pkg/github/pullrequests_test.go
The `get_pull_request_files` tool currently retrieves only the first 30 files with diffs of any PR that contains more than 30 files. This is a limitation because large PRs with many files cannot be fully analyzed.
Added pagination support to the `get_pull_request_files` tool by:
- Adding `WithPagination()` to the tool definition
- Using `OptionalPaginationParams(request)` to handle `page` and `perPage` parameters
- Passing pagination parameters to the GitHub API `ListFiles` call
- Following the same pattern used by other paginated tools in the codebase
```go
// Added WithPagination() to tool definition
WithPagination(),
// Added pagination parameter handling
pagination, err := OptionalPaginationParams(request)
if err != nil {
return mcp.NewToolResultError(err.Error()), nil
}
// Updated …
```
=> feat: add pagination support to get_pull_request_files tool

pkg/github/__toolsnaps__/search_users.snap, pkg/github/search.go, pkg/github/search_test.go, pkg/github/tools.go
In order to make separation of certain objects more clear we should separate them. This means orgs and users are not the same.
A follow-up will be to separate issue and PR search by also scoping the queries and producing separate functions. It is best for the LLM that it has clear boundaries, and concepts are consistent, rather than accepting the legacy API quirks.
=> Separate org and user search

pkg/github/__toolsnaps__/search_issues.snap, pkg/github/__toolsnaps__/search_pull_requests.snap, pkg/github/issues.go, pkg/github/issues_test.go, pkg/github/pullrequests.go, pkg/github/pullrequests_test.go, pkg/github/search_utils.go, pkg/github/tools.go
Add search pull requests tool.
Fixes https://github.com/github/github-mcp-server/issues/462 and https://github.com/github/github-mcp-server/issues/334
=> Add search pull requests tool

README.md, pkg/github/actions.go, pkg/github/actions_test.go
This PR adds a new option to tail logs. 
Closes: https://github.com/github/github-mcp-server/issues/608
=> Add tail logs option

pkg/github/discussions.go, pkg/github/discussions_test.go
Fixes bug in `get_discussion` which caused tool error and returned:
> Field 'state' doesn't exist on type 'Discussion'
- Removed "state" field from query and response
- Used `github.Discussion` object instead of `github.Issue`
- Corrected "labels" to "category" in response
- Tool arguments and descriptions unchanged.
<details><summary>Before with bug</summary>
</details>
=> fix: get_discussion graphQL invalid field

CONTRIBUTING.md, README.md, pkg/github/__toolsnaps__/get_me.snap, pkg/github/context_tools.go
This pr:
- removes the `reason` argument for `get_me` tool call.
- adds a bit of information to the contribution guide.
- prompt changes
- encourage the llm to use this command in a chain if additional information is needed
- it is unnecesary to tell the llm to not call a tool again which it still has the tool response cached in the session
=> Remove redundant param for get_me and update contribution guide

pkg/github/__toolsnaps__/list_pull_requests.snap, pkg/github/pullrequests.go
This PR fixes a buggy behaviour which occurs when the user uses the Github MCP to query PRs by author (e.g. by asking "show me my last 10 PRs in repo xyz") and the MCP uses the `list_pull_requests` tool, which does not support author-specific queries due to constraints in the Github API (see official API [docs](https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#list-pull-requests)). 
To fix this issue, this PR changes the `list_pull_requests` tool description to ensure that the `search_pull_requests` tool is selected when the user requests PRs by author.
This solution seems to work as expected across all models. The only caveat is that o4-mini sometimes doesn't seem to always use the `get_me` tool to get the user information before using the `search_pull_requests` tool (it …
=> Tommy/(Bug-fix): adjust tool description to account for author in prompt

pkg/github/repositories.go, pkg/github/repositories_test.go
Adds additional steps to the end of `get_file_content` so that if the provided path wasn't found, then we check the Git Tree for possible matching paths. A path matches if it ends with the provided path.
- Added additional processing to the end of `get_file_content` so that if previous attempts to get the file/dir fail, then:
- Get the recursive Git Tree containing tree and blob paths
- Filters the tree for entries matching the input `path` arg. New func `filterTree`.
- If any matches, returns a tool result containing the resolved ref & sha and matching paths. Else resume and return tool error result as normal.
- Refactored logic for resolving input `ref` and `sha` into a function `resolveGitReference`.  This still handles refs of the form `refs/tags/{tag}`, `refs/heads/{branch}`, …
=> `get_file_content` Match Paths in Git Tree if Full Path Unknown

CONTRIBUTING.md, README.md, docs/installation-guides/README.md, docs/installation-guides/install-claude.md, docs/installation-guides/install-cursor.md, docs/installation-guides/install-other-copilot-ides.md, docs/installation-guides/install-windsurf.md, docs/policies-and-governance.md
This PR improves the docs structure and clarity for the GitHub MCP Server, and add a policies and governance doc for info on control mechanisms.
- **Reorganized README** for better clarity and navigation
- **Created dedicated installation guides** for non-VS Code host applications:
- `/docs/installation-guides/install-other-copilot-ides.md` - JetBrains, Visual Studio, Eclipse, Xcode
- `/docs/installation-guides/install-claude.md` - Claude Web, Desktop, and Code CLI
- `/docs/installation-guides/install-cursor.md` - Cursor IDE
- `/docs/installation-guides/install-windsurf.md` - Windsurf IDE
- **Updated contribution guidelines** to clarify approval criteria for different types of requests
- **Added policies and governance documentation** at `/docs/policies-and-governance.md`
These changes …
=> Reorganize README, add dedicated install guides, include policies and governance info for the github server

README.md, docs/installation-guides/install-cursor.md, docs/installation-guides/install-other-copilot-ides.md
Removed reference to GitHub.com in the installation guide. The GitHub server is available to Coding Agent by default, without installation needed.
Closes: Quick tune
=> Update installation guide for GitHub MCP Server

cmd/mcpcurl/main.go
- FYI:https://json-schema.org/understanding-json-schema/reference/numeric#integer
Closes: #687
=> fix: make mcpcurl support "integer" type (#687)

cmd/mcpcurl/README.md
Adds installation instructions for mcpcurl CLI documentation.
=> Added installation instructions for mcpcurl

README.md, pkg/github/__toolsnaps__/update_pull_request.snap, pkg/github/pullrequests.go, pkg/github/pullrequests_test.go, pkg/github/tools.go
Closes: https://github.com/github/github-mcp-server/issues/501 and https://github.com/github/github-mcp-server/pull/423
This is a copy of the comment in issue 501:
I've had a look at implementing this as an extension of the `update_pull_request` tool (using GraphQL). I've chosen to use a new `draft` parameter as a boolean for this for a few reasons:
- In the GraphQL spec for pull requests, 'draft' is separate to 'state' as a PR can be both closed as a draft, open as ready for review, etc (ref:
```
"""
The possible states of a pull request.
"""
enum PullRequestState {
"""
A pull request that has been closed without being merged.
"""
CLOSED
"""
A pull request that has been closed by being merged.
"""
MERGED
"""
A pull request that is still open.
"""
OPEN
}
```  
```
Identifies if the pull …
```
=> Add updating draft state to `update_pull_request` tool

pkg/github/issues.go
Closes: [#350](https://github.com/orgs/github/projects/21466?pane=issue&itemId=123147313&issue=github%7Ccopilot-agent-services%7C350)
[Now that go-github is on v74](https://github.com/github/github-mcp-server/pull/826), we can use go-github to remove sub issues instead of making raw HTTP requests to the Github API. This PR updates the tool to use `go-github`
**Demo**
=> Update `remove_sub_issue` tool to use go-github

README.md, pkg/github/__toolsnaps__/get_release_by_tag.snap, pkg/github/repositories.go, pkg/github/repositories_test.go, pkg/github/tools.go
Closes: #461 exhaustively, and part of #559 and #150 
This PR introduces the new `get_release_by_tag` tool, allowing users to fetch and interrogate a specific release by its tag name, which can be especially useful when the version is already known. It includes the tool implementation and corresponding tests. 
**Demo**
=> Add get_release_by_tag tool

docs/installation-guides/install-cursor.md
Closes: #860 
The current installation links for both the remote and the local MCP is broken due to an update on Cursor's side. This PR updates the link to a working one. The links were generated using Cursor's [guide](https://docs.cursor.com/en/tools/developers)
=> Update Cursor installation link

README.md, pkg/github/__toolsnaps__/get_project.snap, pkg/github/__toolsnaps__/list_project_fields.snap, pkg/github/__toolsnaps__/list_projects.snap, pkg/github/projects.go, pkg/github/projects_test.go, pkg/github/tools.go
This pr:
1. Removes (for now) pagination for `list_projects` tool
2. Adds tools:
- `get_project` tool for user and org
- `list_project_fields` tool for user and org
Implements https://github.com/github/github-mcp-server/issues/44
Implements new projects V2 API. FYI implementation of project tools will use google/go-github when they implement the new API.
Pagination will be added in the next step.
=> Add tools for Projects V2
